#!/bin/sh

# The test below was generated by Codex to regression-test a
# specific bug it had found in my seek() algorithms.

# Regression test for binary file seeks after a buffered read.
#
# This covers two cases:
#   - seek(0, SEEK_CUR) must account for unread buffered bytes before
#     invalidating the buffer.
#   - seek(offset, SEEK_SET) must not apply the SEEK_CUR-only correction.

set -u

srcdir=${srcdir:-.}
evilcandy=${EVILCANDY:-./evilcandy}

case $evilcandy in
    /*) ;;
    *) evilcandy=$(pwd)/$evilcandy ;;
esac

case $srcdir in
    /*) top_srcdir=$srcdir ;;
    *) top_srcdir=$(pwd)/$srcdir ;;
esac

if [ ! -x "$evilcandy" ]; then
    echo "$0: cannot execute $evilcandy" >&2
    exit 1
fi

tmpbase=${TMPDIR:-/tmp}
tmpdir=$tmpbase/evilcandy-binseek-$$

if ! (umask 077 && mkdir "$tmpdir"); then
    echo "$0: cannot create temporary directory $tmpdir" >&2
    exit 1
fi

cleanup() {
    rm -f "$tmpdir/data.bin" "$tmpdir/test.evc" \
          "$tmpdir/actual.txt" "$tmpdir/expected.txt"
    rmdir "$tmpdir" 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

evc_sq() {
    # Quote a shell string for EvilCandy single-quoted string literals.
    printf "%s" "$1" | sed "s/'/\\\\'/g"
}

datafile=$tmpdir/data.bin
script=$tmpdir/test.evc
actual=$tmpdir/actual.txt
expected=$tmpdir/expected.txt

printf "abcdefghijklmnopqrstuvwxyz" > "$datafile" || exit 1

datafile_evc=$(evc_sq "$datafile")
io_evc=$(evc_sq "$top_srcdir/lib/io.evc")

cat > "$script" <<EOF
let io = importfile('$io_evc');

function emit(name, value) {
    print(f'{name}={value}');
}

let f = open('$datafile_evc', 'rb');
f.read(3);
emit('default-set-pos', f.seek(0));
emit('default-set-next', f.read(1));

f = open('$datafile_evc', 'rb');
f.read(3);
emit('cur-zero-tell', f.tell());
emit('cur-zero-pos', f.seek(0, io.SEEK_CUR));
emit('cur-zero-next', f.read(1));

f = open('$datafile_evc', 'rb');
f.read(3);
emit('cur-plus-pos', f.seek(2, io.SEEK_CUR));
emit('cur-plus-next', f.read(1));

f = open('$datafile_evc', 'rb');
f.read(3);
emit('explicit-set-pos', f.seek(5, io.SEEK_SET));
emit('explicit-set-next', f.read(1));
EOF

cat > "$expected" <<'EOF'
default-set-pos=0
default-set-next=b'a'
cur-zero-tell=3
cur-zero-pos=3
cur-zero-next=b'd'
cur-plus-pos=5
cur-plus-next=b'f'
explicit-set-pos=5
explicit-set-next=b'f'
EOF

if ! "$evilcandy" "$script" > "$actual"; then
    result=$?
    echo "$0: EvilCandy test script failed with status $result" >&2
    cat "$actual" >&2
    exit "$result"
fi

if cmp -s "$expected" "$actual"; then
    echo "binary seek buffer regression: success"
else
    echo "$0: unexpected output" >&2
    diff -u "$expected" "$actual" >&2
    exit 1
fi


