#!/bin/sh

# The test below was generated by Codex to regression-test a
# specific bug it had found in my seek() algorithms.

# Regression test for text-file seeks after a read reaches EOF.
#
# Once a text file has observed EOF, seek() must clear the latched EOF
# state so later reads can refill the buffer from the new position.

set -u

srcdir=${srcdir:-.}
evilcandy=${EVILCANDY:-./evilcandy}

case $evilcandy in
    /*) ;;
    *) evilcandy=$(pwd)/$evilcandy ;;
esac

case $srcdir in
    /*) top_srcdir=$srcdir ;;
    *) top_srcdir=$(pwd)/$srcdir ;;
esac

if [ ! -x "$evilcandy" ]; then
    echo "$0: cannot execute $evilcandy" >&2
    exit 1
fi

tmpbase=${TMPDIR:-/tmp}
tmpdir=$tmpbase/evilcandy-textseek-$$

if ! (umask 077 && mkdir "$tmpdir"); then
    echo "$0: cannot create temporary directory $tmpdir" >&2
    exit 1
fi

cleanup() {
    rm -f "$tmpdir/data.txt" "$tmpdir/test.evc" \
          "$tmpdir/actual.txt" "$tmpdir/expected.txt"
    rmdir "$tmpdir" 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

evc_sq() {
    # Quote a shell string for EvilCandy single-quoted string literals.
    printf "%s" "$1" | sed "s/'/\\\\'/g"
}

datafile=$tmpdir/data.txt
script=$tmpdir/test.evc
actual=$tmpdir/actual.txt
expected=$tmpdir/expected.txt

printf "abcdef" > "$datafile" || exit 1

datafile_evc=$(evc_sq "$datafile")
io_evc=$(evc_sq "$top_srcdir/lib/io.evc")

cat > "$script" <<EOF
let io = importfile('$io_evc');

function emit(name, value) {
    print(f'{name}=<{value}>');
}

let f = open('$datafile_evc', 'r');
emit('initial-read', f.read());
emit('after-eof', f.read(1));
emit('default-set-pos', f.seek(0));
emit('default-set-next', f.read(1));

f = open('$datafile_evc', 'r');
f.read();
emit('explicit-set-pos', f.seek(0, io.SEEK_SET));
emit('explicit-set-next', f.read(1));
EOF

cat > "$expected" <<'EOF'
initial-read=<abcdef>
after-eof=<>
default-set-pos=<0>
default-set-next=<a>
explicit-set-pos=<0>
explicit-set-next=<a>
EOF

if ! "$evilcandy" "$script" > "$actual"; then
    result=$?
    echo "$0: EvilCandy test script failed with status $result" >&2
    cat "$actual" >&2
    exit "$result"
fi

if cmp -s "$expected" "$actual"; then
    echo "text seek EOF regression: success"
else
    echo "$0: unexpected output" >&2
    diff -u "$expected" "$actual" >&2
    exit 1
fi

